// TODO: Remove this entire file when backend is integrated
// This is only for frontend development and testing
export const initializeDemoGroups = () => {
  const existingGroups = JSON.parse(localStorage.getItem("studyGroups")) || [];
  const userId = localStorage.getItem("userId") || "user-demo";
  
  // Demo groups for frontend development only
  if (true) {
    const demoGroups = [
      {
        id: "demo1",
        name: "CS101 Advanced Topics",
        description: "Discussion on advanced computer science concepts and problem solving",
        code: "CS101",
        coursename: "Computer Science 101",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user2", "user3"],
        memberCount: 3,
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo2",
        name: "MATH201 Calculus Study",
        description: "Collaborative learning for calculus II - homework help and exam prep",
        code: "MATH201",
        coursename: "Calculus II",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user4", "user5", "user6"],
        memberCount: 4,
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo3",
        name: "Physics Lab Partners",
        description: "Find lab partners and discuss physics experiments",
        code: "PHY101",
        coursename: "Physics I",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user7"],
        memberCount: 2,
        createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo4",
        name: "Data Structures Mastery",
        description: "Master data structures and algorithms for interviews",
        code: "CS102",
        coursename: "Data Structures",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user8", "user9", "user10", "user11"],
        memberCount: 5,
        createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo5",
        name: "English Literature Discussion",
        description: "Discuss classic and modern literature, share book reviews",
        code: "ENG101",
        coursename: "English Literature",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user12", "user13"],
        memberCount: 3,
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo6",
        name: "Algorithms & Problem Solving",
        description: "Practice coding problems and discuss algorithm optimization",
        code: "CS103",
        coursename: "Algorithms",
        privacy: "PRIVATE",
        createdBy: "admin-user",
        members: ["admin-user", "user14"],
        memberCount: 2,
        createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo7",
        name: "Operating Systems Concepts",
        description: "Deep dive into OS concepts, processes, threads, and memory management",
        code: "CS104",
        coursename: "Operating Systems",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user15", "user16", "user17"],
        memberCount: 4,
        createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo8",
        name: "Database Design & SQL",
        description: "Learn database design patterns and SQL optimization techniques",
        code: "CS105",
        coursename: "Database Management Systems",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user18"],
        memberCount: 2,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo9",
        name: "Computer Networks Basics",
        description: "Understanding networking protocols, TCP/IP, and network architecture",
        code: "CS106",
        coursename: "Computer Networks",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user19", "user20", "user21"],
        memberCount: 4,
        createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo10",
        name: "Digital Electronics Lab",
        description: "Discuss digital circuits, logic gates, and microcontroller projects",
        code: "ECE101",
        coursename: "Digital Electronics",
        privacy: "PUBLIC",
        createdBy: "admin-user",
        members: ["admin-user", "user22"],
        memberCount: 2,
        createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo11",
        name: "Web Development Masters",
        description: "Advanced web development with React, Node.js, and databases",
        code: "CS107",
        coursename: "Web Development",
        privacy: "PRIVATE",
        createdBy: "admin-user",
        members: ["admin-user", "user23"],
        memberCount: 2,
        createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: "demo12",
        name: "Mobile App Development",
        description: "Building iOS and Android apps with Flutter and React Native",
        code: "CS108",
        coursename: "Mobile Development",
        privacy: "PRIVATE",
        createdBy: "admin-user",
        members: ["admin-user", "user24", "user25"],
        memberCount: 3,
        createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      },
    ];

    localStorage.setItem("studyGroups", JSON.stringify(demoGroups));
  }
};
